### ISSUE TITLE
Buttons on wish list are messed up - ipad pro view?

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#10]
![screen shot 2018-02-12 at 10 17 46 am](https://user-images.githubusercontent.com/11448089/36112279-032ea042-0fde-11e8-9dfa-dcee4a2353cb.png)

![screen shot 2018-02-12 at 10 21 24 am](https://user-images.githubusercontent.com/11448089/36112443-8287541a-0fde-11e8-9250-97ca30f3ce3f.png)

**Comment by mivajenn** [comment]
In Firefox, full view, the buttons expand into the white separation space. I don't think they should? 
![screen shot 2018-02-12 at 11 01 36 am](https://user-images.githubusercontent.com/11448089/36114224-375124f2-0fe4-11e8-93d1-13d2fa6b065d.png)

**Comment by influxweb** [comment]
The layout has been updated in the demonstration site. Add this code to the Wish List Page section of the theme.css file and the class `t-wish-list__item` to the `x-product-list__item` element in the code to correct.

```css
.t-wish-list__item .c-control-group__button {
	flex: 1 1 50%;
	padding-right: 0;
	padding-left: 0;
}
```
