### ISSUE TITLE
iOS Input Zooming

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/readytheme-shadows#103]
## Current Behavior
The dreaded "zoom-in" issue with iOS devices has reared its head again. If the browser is uncertain of the font size for the input, it will zoom it in for the user. Unfortunately, it doesn't always zoom back out when filled in.

## Correcting the Issue
To make the update, without applying the latest release, you will need to update the code in **`build -> core -> css -> elements -> _forms.scss`:**

```scss
/* ==========================================================================
   ELEMENTS / FORMS
   ========================================================================== */

/**
 * Semantically, we'd like all forms to be built with FIELDSETs and LEGENDs, but
 * we currently don't want to visually see them.
 *
 * 1. Visually hide content, leaving it accessible to screen readers and ATs.
 *    http://snook.ca/archives/html_and_css/hiding-content-for-accessibility
 */
fieldset {
	margin-bottom: 0;
	border: none;
}

legend { /* [1] */
	width: 1px;
	height: auto;
	margin: 0;
	padding: 0;
	position: absolute;
	overflow: hidden;
	border: 0;
	clip: rect(0 0 0 0);
	white-space: nowrap;
}

/**
 * Make sure our form elements don't use any UA-specific font styles: we want
 * them to use ours. This may need reverting as more design information becomes
 * available, and we start putting together more complete forms.
 */
input {
	font: inherit;
}

button,
input,
html,
select,
textarea {
	letter-spacing: 0.05em;
}

/**
 * Ensure that, when focused, the iOS Input Zoom doesn't happen.
 */
input:not([type="checkbox"]):not([type="radio"]):focus,
select:focus,
textarea:focus {
	font-size: 16px;
}
```
