### ISSUE TITLE
iOS Input Zooming...Revisited

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/readytheme-shadows#109]
## Current Behavior
While addressing issue #103, the browsers got smarter. While hovering and activating an input, select, or textarea, the `focus` of the element is triggered as well. This can cause a visible change in the input as the text size changes. This will be corrected by adding a `hover` negation clause added to the previous fix.

## Correcting the Issue
To make the update, without applying the latest release, you will need to update the code in **`build -> core -> css -> elements -> _forms.scss`:**

```scss
/* ==========================================================================
   ELEMENTS / FORMS
   ========================================================================== */

/**
 * Semantically, we'd like all forms to be built with FIELDSETs and LEGENDs, but
 * we currently don't want to visually see them.
 *
 * 1. Visually hide content, leaving it accessible to screen readers and ATs.
 *    http://snook.ca/archives/html_and_css/hiding-content-for-accessibility
 */
fieldset {
	margin-bottom: 0;
	border: none;
}

legend { /* [1] */
	width: 1px;
	height: auto;
	margin: 0;
	padding: 0;
	position: absolute;
	overflow: hidden;
	border: 0;
	clip: rect(0 0 0 0);
	white-space: nowrap;
}

/**
 * Make sure our form elements don't use any UA-specific font styles: we want
 * them to use ours. This may need reverting as more design information becomes
 * available, and we start putting together more complete forms.
 */
input {
	font: inherit;
}

button,
input,
html,
select,
textarea {
	letter-spacing: 0.05em;
}

/**
 * Ensure that, when focused, the iOS Input Zoom doesn't happen.
 */
@media screen and (-webkit-min-device-pixel-ratio: 2) {
	input[type="color"]:focus,
	input[type="date"]:focus,
	input[type="datetime"]:focus,
	input[type="datetime-local"]:focus,
	input[type="email"]:focus,
	input[type="month"]:focus,
	input[type="number"]:focus,
	input[type="password"]:focus,
	input[type="search"]:focus,
	input[type="tel"]:focus,
	input[type="text"]:focus,
	input[type="time"]:focus,
	input[type="url"]:focus,
	input[type="week"]:focus,
	select:focus,
	textarea:focus {
		font-size: 16px;
	}
}
```
