### ISSUE TITLE
ORDL: Logo Off-Center on Mobile

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/readytheme-shadows#118]
## Current Behavior
_As reported on the forums: https://www.miva.com/forums/node/715239_

On the ORDL screen the logo is off center on mobile. It looks like the themes.css is missing the same styles as the other checkout pages.

## Correcting the Issue
To make the update, without applying the latest release, you will need to update the code in **`build -> ui -> css -> theme.scss`:**

```scss
...

@media (max-width: 59.9em) {
	.t-page-ordl .t-site-header__logo,
	.t-page-ocst .t-site-header__logo,
	.t-page-osel .t-site-header__logo,
	.t-page-opay .t-site-header__logo {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
}

...
```
