### ISSUE TITLE
Off canvas sub navigation fix

### ISSUE THREAD

**Issue by cam424** [mivaecommerce/readytheme-shadows#24]
When viewing the Shadows theme in less than 960px, the support_navigation links were inaccessible while clicked into a second level nav list. 

## Expected Behavior
I wasn't sure if they were supposed to be accessible, but from the looks of things, the sub navs are meant to entirely take over the off canvas area since the `min-height` is set to 100% on the `.x-transfigure-navigation__row` class.

`.x-transfigure-navigation__row` should take up the entire vertical height to prevent the support navigation from appearing broken.

## Current Behavior
Currently, if the previous nav level list is longer than the sub navigation list, the lower list items of the first nav still appear below the end of the second nav as the `min-height` is not enough to fill the area.

## Attempted Fixes
Tried to submit a PR but lack permissions for the repo. The following additions fix the issue and are supported by all modern browsers. Adds vertical height units to prevent parent lists from showing while sub navs are active, utilizing the existing `overflow-y` to allow for scrolling when height of browser is less than the height of the nav list. Added a background color to hide the parent list content. --Bolded my additions to the rulesets.

`
@media screen and (max-width: 59.9em) {

	/* Off Canvas Nav Fix */
	.x-transfigure-navigation__content {
		**height: 100vh;**
		padding-top: 1em;
		padding-bottom: 1em;
	}  /*** found in mm5/shadows/ui/css/theme-styles.css ***/

	.x-transfigure-navigation__row,
	.x-transfigure-navigation__row .c-navigation__row,
	.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type {
		display: block;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		**height: 100vh;**
		min-height: 100%;
		**background-color: #fff;**
		list-style: none;
		-webkit-overflow-scrolling: touch;
		overflow-x: hidden;
		overflow-y: auto;
		transition: transform 0.3s;
	} /*** found in mm5/shadows/extensions/navigation/transfigure-navigation.css ***/

}
`

## Steps to Reproduce (for bugs)

1. Visit https://shadows.mivareadythemes.com
2. Reduce browser below 960px
3. Click hamburger icon to open off canvas nav.
4. Click Category 1
5. Note that when sub nav becomes active, the support navigation links are no longer clickable.

*--When adding more links to this category, they overlap the support nav links as well.

## Context
This fix will create a more expected UX for all clients.

## Your Environment
Tested on Mac in Chrome, Firefox and Safari

**Comment by influxweb** [comment]
Thank you for finding this bu @cam424 . I will update the code and run it through testing. It will be included in the next maintenance release.

**Comment by influxweb** [comment]
Here is the updated `transfigure-navigation.css` file:
```css
/* ==========================================================================
   EXTENSIONS / NAVIGATION / TRANSFIGURE NAVIGATION
   ========================================================================== */

@media screen and (max-width: 59.9em) {
	.has-open-main-menu,
	.has-open-main-menu body {
		overflow: hidden;
	}
	
	.x-transfigure-navigation {
		padding: 0;
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: -100vw;
		-webkit-backface-visibility: hidden;
		backface-visibility: hidden;
		background-color: rgba(0, 0, 0, 0);
		opacity: 0;
		overflow: hidden;
		transition: all ease-out 0.2s;
		-webkit-transform: scaleX(0);
		-ms-transform: scaleX(0);
		transform: scaleX(0);
		transform-origin: left;
		z-index: -1;
	}
	
		.x-transfigure-navigation.is-open {
			left: 0;
			background: rgba(0, 0, 0, 0.65);
			opacity: 1;
			transition: all ease-in 0.2s;
			-webkit-transform: scaleX(1);
			-ms-transform: scaleX(1);
			transform: scaleX(1);
			z-index: 2;
		}
	
		.x-transfigure-navigation__wrap {
			max-width: 22.5rem;
			min-height: 100%;
			-webkit-overflow-scrolling: touch;
			overflow-x: hidden;
			overflow-y: auto;
			background-color: #fff;
		}
		
			.x-transfigure-navigation__header {}
		
				.x-transfigure-navigation__header .c-button {
					padding: calc(1em - 1px);
				}
		
			.x-transfigure-navigation__content {
				position: relative;
			}
			
				.x-transfigure-navigation__row,
				.x-transfigure-navigation__row .c-navigation__row,
				.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type {
					display: block;
					position: absolute;
					top: 0;
					left: 0;
					width: 100%;
					min-height: 100%;
					background-color: #fff;
					list-style: none;
					transition: transform 0.3s;
				}
				
					.x-transfigure-navigation .c-navigation__list {
						position: static;
					}
				
						.x-transfigure-navigation .c-navigation__list:hover > .c-navigation__row {
							display: block;
							box-shadow: none;
						}
			
						.x-transfigure-navigation .c-navigation__link {
							display: flex;
							height: 3.75rem;
							padding: 0 0 0 1rem;
							align-items: center;
							justify-content: space-between;
							-webkit-backface-visibility: hidden;
							backface-visibility: hidden;
							border: 0 solid #d3d3d3;
							border-top-width: 1px;
							overflow: hidden;
							text-overflow: ellipsis;
							-webkit-transform: translateZ(0);
							-ms-transform: translateZ(0);
							transform: translateZ(0);
							transition: all 0.3s;
							white-space: nowrap;
						}
						
						.x-transfigure-navigation .c-navigation__row:nth-child(2) .c-navigation__link,
						.x-transfigure-navigation .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type .c-navigation__link {
							padding-left: 1rem;
						}
						
						.x-transfigure-navigation__row .c-navigation__list:first-of-type > .c-navigation__link,
						.x-transfigure-navigation__row .c-navigation__row .c-navigation__list:first-of-type > .c-navigation__link {
							/*border-top-width: 0;*/
						}
						
						.x-transfigure-navigation__row .c-navigation__list:last-of-type > .c-navigation__link,
						.x-transfigure-navigation__row .c-navigation__row .c-navigation__list:last-of-type > .c-navigation__link {
							border-bottom-width: 1px;
						}
						
				.x-transfigure-navigation__row.is-hidden,
				.x-transfigure-navigation__row .c-navigation__row.is-hidden {
					-webkit-transform: translateX(100%);
					-ms-transform: translateX(100%);
					transform: translateX(100%);
				}
				
				.x-transfigure-navigation__row.is-hidden > .cmp-primary-navigation__title,
				.x-transfigure-navigation__row.show-next > .cmp-primary-navigation__title,
				.x-transfigure-navigation__row.is-hidden > .c-navigation__list > .c-navigation__link,
				.x-transfigure-navigation__row.show-next > .c-navigation__list > .c-navigation__link,
				.x-transfigure-navigation__row .c-navigation__row.is-hidden > .c-navigation__list > .c-navigation__link,
				.x-transfigure-navigation__row .c-navigation__row.show-next > .c-navigation__list > .c-navigation__link {
					opacity: 0;
				}
				
				.x-transfigure-navigation__row.show-next > .c-navigation__list > .c-navigation__link,
				.x-transfigure-navigation__row .c-navigation__row.show-next > .c-navigation__list > .c-navigation__link {
					-webkit-transform: translateX(-100%);
					-ms-transform: translateX(-100%);
					transform: translateX(-100%);
				}
				
				.x-transfigure-navigation .c-navigation__link-carat {
					display: none;
				}
				
					.x-transfigure-navigation .has-child-menu .c-navigation__link-carat {
						display: inline-flex;
						align-self: stretch;
					}
					
						.x-transfigure-navigation .c-navigation__link-carat > * {
							display: flex;
							width: 4rem;
							align-items: center;
							justify-content: center;
							font-size: 0.75rem;
						}


				.x-transfigure-navigation__footer {
					padding: 1rem;
					font-size: 0.75rem;
					list-style: none;
					border-top: 1px solid #d3d3d3;
				}

					.x-transfigure-navigation__footer-link {
						display: block;
						padding-top: 1em;
						padding-bottom: 1em;
						font-weight: 500;
						line-height: 2;
					}
}


@media screen and (min-width: 60em) {
	.x-transfigure-navigation__row .c-navigation__row {
		display: none;
		width: auto;
		position: absolute;
		white-space: nowrap;
		z-index: 100;
	}

	.x-transfigure-navigation > .c-navigation__row {
		display: flex;
	}
	
		.x-transfigure-navigation .c-navigation__link {
			display: flex;
			align-items: center;
			justify-content: space-around;
		}
	
		.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__list {
			text-align: left;
		}
	
		.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type {
			top: 0;
			left: 100%;
			z-index: 200;
		}
		
		.x-transfigure-navigation .c-navigation__row:nth-child(2) .c-navigation__link,
		.x-transfigure-navigation .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type .c-navigation__link {
			justify-content: space-between;
		}
		
		.x-transfigure-navigation .c-navigation__list:hover > .c-navigation__row {
			display: table;
			box-shadow: 1px 1px 0.25em 0 rgba(15, 15, 15, 0.5);
		}
		
			.x-transfigure-navigation__row .is-off-screen .c-navigation__row:nth-child(2) .c-navigation__row {
				left: auto;
				right: 100%;
				box-shadow: -1px 1px 0.25em 0 rgba(15, 15, 15, 0.5);
			}
		
			.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__row .c-navigation__link,
			.x-transfigure-navigation__row .c-navigation__row:nth-child(2) .c-navigation__row:last-of-type .c-navigation__link {
				padding-left: 1em;
			}
		
		.x-transfigure-navigation .c-navigation__link-carat {
			font-size: 0.5em;
			-webkit-transform: rotate(90deg);
			-ms-transform: rotate(90deg);
			transform: rotate(90deg);
		}
	
		.x-transfigure-navigation .c-navigation__row:nth-child(2) .c-navigation__link-carat {
			-webkit-transform: rotate(0deg);
			-ms-transform: rotate(0deg);
			transform: rotate(0deg);
		}
}
```
