### ISSUE TITLE
Shadows Body Scroll iPhone Issue

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/readytheme-shadows#28]
From Colin at Glendale Design:

> ...testing we noticed that on an iPhone the site won't let the user scroll the page until you wait a bit (something seems to need to finish loading before the body is allowed to scroll) or you can bypass this by pinching the screen (triggers resize I guess) or clicking the mini cart or mobile menu. This has been verified on multiple iPhone...

This appears to have been caused by iOS not fully rendering the off-screen navigation as "invisible". The following update to the `transfiguration-navigation.css` file will correct the issue. This update is included in the fix for #24 

```css
	.x-transfigure-navigation {
		padding: 0;
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: -100vw;
		-webkit-backface-visibility: hidden;
		backface-visibility: hidden;
		background-color: rgba(0, 0, 0, 0);
		opacity: 0;
		overflow: hidden;
		transition: all ease-out 0.2s;
		-webkit-transform: scaleX(0);
		-ms-transform: scaleX(0);
		transform: scaleX(0);
		transform-origin: left;
		z-index: -1;
	}
	
		.x-transfigure-navigation.is-open {
			left: 0;
			background: rgba(0, 0, 0, 0.65);
			opacity: 1;
			transition: all ease-in 0.2s;
			-webkit-transform: scaleX(1);
			-ms-transform: scaleX(1);
			transform: scaleX(1);
			z-index: 2;
		}
```
