### ISSUE TITLE
Additional Breakpoint

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/readytheme-shadows#49]
Currently, at the top-end of the scale, we have a breakpoint at 60em (960px) and then a final one at 90em (1440px). As we have seen new devices on the market, such as the larger iPad Pro, which have screen sizes between these two points, I have updated the `display.css`, `grids.css`, and `widths.css` file to add an x-large breakpoint at 75em (1200px).

Additionally, I have added breakpoint display as a hidden `body::before` element which can be accessed via JavaScript. These changes are within the `resets.css` and `scripts.js` files.

I have added this enhancement and it will be included in the next maintenance release. To make the update prior to the next release, you will need to update the contents of the following files via FTP:

**Comment by influxweb** [comment]
**`mm5/themes/shadows/core/css/utilities/display.css`**
```css
/* ==========================================================================
   UTILITIES / DISPLAY
   ========================================================================== */

.u-overflow-hidden {
	overflow: hidden;
}

/**
 * Hide only visually, but have it available for screen readers:
 * http://snook.ca/archives/html_and_css/hiding-content-for-accessibility
 */
.u-hide-visually {
	width: 1px;
	height: 1px;
	margin: -1px;
	padding: 0;
	position: absolute;
	overflow: hidden;
	border: 0;
	clip: rect(0 0 0 0);
	white-space: nowrap;
}

	.u-hide-visually.focusable:active,
	.u-hide-visually.focusable:focus {
		width: auto;
		height: auto;
		margin: 0;
		overflow: visible;
		position: static;
		clip: auto;
		white-space: inherit;
	}


/**
 * Hide visually and from screen readers.
 */
[aria-hidden='true'],
.u-hidden {
	display: none;
}


/**
 * Hidden visually but maintains the layout.
 */
.u-invisible {
	visibility: hidden;
}


/**
 * Various utility classes to show the content.
 */
.u-flex {
	display: flex;
}

.u-block,
.u-shown {
	display: block;
}

.u-inline {
	display: inline;
}

.u-inline-block {
	display: inline-block;
}

.u-visible {
	visibility: visible;
}


/* Small Breakpoint [40em = 640px]
   =========================================== */
@media screen and (min-width: 40em) {
	.u-hidden--s {
		display: none;
	}
	
	.u-invisible--s {
		visibility: hidden;
	}
	
	.u-flex--s {
		display: flex;
	}
	
	.u-block--s,
	.u-shown--s {
		display: block;
	}
	
	.u-inline--s {
		display: inline;
	}
	
	.u-inline-block--s {
		display: inline-block;
	}
	
	.u-visible--s {
		visibility: visible;
	}
}


/* Medium Breakpoint [48em = 768px]
   =========================================== */
@media screen and (min-width: 48em) {
	.u-hidden--m {
		display: none;
	}
	
	.u-invisible--m {
		visibility: hidden;
	}
	
	.u-flex--m {
		display: flex;
	}
	
	.u-block--m,
	.u-shown--m {
		display: block;
	}
	
	.u-inline--m {
		display: inline;
	}
	
	.u-inline-block--m {
		display: inline-block;
	}
	
	.u-visible--m {
		visibility: visible;
	}
}


/* Large Breakpoint [60em = 960px]
   =========================================== */
@media screen and (min-width: 60em) {
	.u-hidden--l {
		display: none;
	}
	
	.u-invisible--l {
		visibility: hidden;
	}
	
	.u-flex--l {
		display: flex;
	}
	
	.u-block--l,
	.u-shown--l {
		display: block;
	}
	
	.u-inline--l {
		display: inline;
	}
	
	.u-inline-block--l {
		display: inline-block;
	}
	
	.u-visible--l {
		visibility: visible;
	}
}


/* Extra-Large Breakpoint [75em = 1200px]
   =========================================== */
@media screen and (min-width: 75em) {
	.u-hidden--xl {
		display: none;
	}
	
	.u-invisible--xl {
		visibility: hidden;
	}
	
	.u-flex--xl {
		display: flex;
	}
	
	.u-block--xl,
	.u-shown--xl {
		display: block;
	}
	
	.u-inline--xl {
		display: inline;
	}
	
	.u-inline-block--xl {
		display: inline-block;
	}
	
	.u-visible--xl {
		visibility: visible;
	}
}


/* Wide-Screen Breakpoint [90em = 1440px]
   =========================================== */
@media screen and (min-width: 90em) {
	.u-hidden--w {
		display: none;
	}
	
	.u-invisible--w {
		visibility: hidden;
	}
	
	.u-flex--w {
		display: flex;
	}
	
	.u-block--w,
	.u-shown--w {
		display: block;
	}
	
	.u-inline--w {
		display: inline;
	}
	
	.u-inline-block--w {
		display: inline-block;
	}
	
	.u-visible--w {
		visibility: visible;
	}
}
```

**Comment by influxweb** [comment]
**`mm5/themes/shadows/core/css/utilities/grids.css`**
```css
/* ==========================================================================
   UTILITIES / GRIDS
   ========================================================================== */

/**
 * A series of utility classes that give an automatic number of columns based
 * on the class used, media breakpoints are included.
 *
 *	<div class="o-layout u-grids-3">
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *	</div>
 *
 * The above will create a three-column structure in which each column will
 * fluidly fill one-third of the width of the parent with the remainder elements
 * wrapping as needed. We can have more complex systems:
 *
 * 	<div class="o-layout u-grids-1 u-grids-3--m">
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 *		<div class="o-layout__item">
 *		</div>
 * 	</div>
 *
 * The above will create a structure in which each column will be 100% width
 * until we enter our medium breakpoint, then they will be one-third the width
 * of the parent container with the remainder elements wrapping as needed.
 */

/* Mobile First
   =========================================== */
.u-grids-1 > .o-layout__item {
	flex-basis: 100%;
	max-width: 100%;
}

.u-grids-2 > .o-layout__item {
	flex-basis: calc(100% / 2);
	max-width: calc(100% / 2);
}

.u-grids-3 > .o-layout__item {
	flex-basis: calc(100% / 3);
	max-width: calc(100% / 3);
}

.u-grids-4 > .o-layout__item {
	flex-basis: calc(100% / 4);
	max-width: calc(100% / 4);
}

.u-grids-5 > .o-layout__item {
	flex-basis: calc(100% / 5);
	max-width: calc(100% / 5);
}

.u-grids-6 > .o-layout__item {
	flex-basis: calc(100% / 6);
	max-width: calc(100% / 6);
}

.u-grids-7 > .o-layout__item {
	flex-basis: calc(100% / 7);
	max-width: calc(100% / 7);
}

.u-grids-8 > .o-layout__item {
	flex-basis: calc(100% / 8);
	max-width: calc(100% / 8);
}

.u-grids-9 > .o-layout__item {
	flex-basis: calc(100% / 9);
	max-width: calc(100% / 9);
}

.u-grids-10 > .o-layout__item {
	flex-basis: calc(100% / 10);
	max-width: calc(100% / 10);
}

.u-grids-11 > .o-layout__item {
	flex-basis: calc(100% / 11);
	max-width: calc(100% / 11);
}

.u-grids-12 > .o-layout__item {
	flex-basis: calc(100% / 12);
	max-width: calc(100% / 12);
}


/* Small Breakpoint [40em = 640px]
   =========================================== */
@media screen and (min-width: 40em) {
	.u-grids-1--s > .o-layout__item {
		flex-basis: 100%;
		max-width: 100%;
	}
	
	.u-grids-2--s > .o-layout__item {
		flex-basis: calc(100% / 2);
		max-width: calc(100% / 2);
	}
	
	.u-grids-3--s > .o-layout__item {
		flex-basis: calc(100% / 3);
		max-width: calc(100% / 3);
	}
	
	.u-grids-4--s > .o-layout__item {
		flex-basis: calc(100% / 4);
		max-width: calc(100% / 4);
	}
	
	.u-grids-5--s > .o-layout__item {
		flex-basis: calc(100% / 5);
		max-width: calc(100% / 5);
	}
	
	.u-grids-6--s > .o-layout__item {
		flex-basis: calc(100% / 6);
		max-width: calc(100% / 6);
	}
	
	.u-grids-7--s > .o-layout__item {
		flex-basis: calc(100% / 7);
		max-width: calc(100% / 7);
	}
	
	.u-grids-8--s > .o-layout__item {
		flex-basis: calc(100% / 8);
		max-width: calc(100% / 8);
	}
	
	.u-grids-9--s > .o-layout__item {
		flex-basis: calc(100% / 9);
		max-width: calc(100% / 9);
	}
	
	.u-grids-10--s > .o-layout__item {
		flex-basis: calc(100% / 10);
		max-width: calc(100% / 10);
	}
	
	.u-grids-11--s > .o-layout__item {
		flex-basis: calc(100% / 11);
		max-width: calc(100% / 11);
	}
	
	.u-grids-12--s > .o-layout__item {
		flex-basis: calc(100% / 12);
		max-width: calc(100% / 12);
	}
}


/* Medium Breakpoint [48em = 768px]
   =========================================== */
@media screen and (min-width: 48em) {
	.u-grids-1--m > .o-layout__item {
		flex-basis: 100%;
		max-width: 100%;
	}
	
	.u-grids-2--m > .o-layout__item {
		flex-basis: calc(100% / 2);
		max-width: calc(100% / 2);
	}
	
	.u-grids-3--m > .o-layout__item {
		flex-basis: calc(100% / 3);
		max-width: calc(100% / 3);
	}
	
	.u-grids-4--m > .o-layout__item {
		flex-basis: calc(100% / 4);
		max-width: calc(100% / 4);
	}
	
	.u-grids-5--m > .o-layout__item {
		flex-basis: calc(100% / 5);
		max-width: calc(100% / 5);
	}
	
	.u-grids-6--m > .o-layout__item {
		flex-basis: calc(100% / 6);
		max-width: calc(100% / 6);
	}
	
	.u-grids-7--m > .o-layout__item {
		flex-basis: calc(100% / 7);
		max-width: calc(100% / 7);
	}
	
	.u-grids-8--m > .o-layout__item {
		flex-basis: calc(100% / 8);
		max-width: calc(100% / 8);
	}
	
	.u-grids-9--m > .o-layout__item {
		flex-basis: calc(100% / 9);
		max-width: calc(100% / 9);
	}
	
	.u-grids-10--m > .o-layout__item {
		flex-basis: calc(100% / 10);
		max-width: calc(100% / 10);
	}
	
	.u-grids-11--m > .o-layout__item {
		flex-basis: calc(100% / 11);
		max-width: calc(100% / 11);
	}
	
	.u-grids-12--m > .o-layout__item {
		flex-basis: calc(100% / 12);
		max-width: calc(100% / 12);
	}
}


/* Large Breakpoint [60em = 960px]
   =========================================== */
@media screen and (min-width: 60em) {
	.u-grids-1--l > .o-layout__item {
		flex-basis: 100%;
		max-width: 100%;
	}
	
	.u-grids-2--l > .o-layout__item {
		flex-basis: calc(100% / 2);
		max-width: calc(100% / 2);
	}
	
	.u-grids-3--l > .o-layout__item {
		flex-basis: calc(100% / 3);
		max-width: calc(100% / 3);
	}
	
	.u-grids-4--l > .o-layout__item {
		flex-basis: calc(100% / 4);
		max-width: calc(100% / 4);
	}
	
	.u-grids-5--l > .o-layout__item {
		flex-basis: calc(100% / 5);
		max-width: calc(100% / 5);
	}
	
	.u-grids-6--l > .o-layout__item {
		flex-basis: calc(100% / 6);
		max-width: calc(100% / 6);
	}
	
	.u-grids-7--l > .o-layout__item {
		flex-basis: calc(100% / 7);
		max-width: calc(100% / 7);
	}
	
	.u-grids-8--l > .o-layout__item {
		flex-basis: calc(100% / 8);
		max-width: calc(100% / 8);
	}
	
	.u-grids-9--l > .o-layout__item {
		flex-basis: calc(100% / 9);
		max-width: calc(100% / 9);
	}
	
	.u-grids-10--l > .o-layout__item {
		flex-basis: calc(100% / 10);
		max-width: calc(100% / 10);
	}
	
	.u-grids-11--l > .o-layout__item {
		flex-basis: calc(100% / 11);
		max-width: calc(100% / 11);
	}
	
	.u-grids-12--l > .o-layout__item {
		flex-basis: calc(100% / 12);
		max-width: calc(100% / 12);
	}
}


/* Extra-Large Breakpoint [75em = 1200px]
   =========================================== */
@media screen and (min-width: 75em) {
	.u-grids-1--xl > .o-layout__item {
		flex-basis: 100%;
		max-width: 100%;
	}
	
	.u-grids-2--xl > .o-layout__item {
		flex-basis: calc(100% / 2);
		max-width: calc(100% / 2);
	}
	
	.u-grids-3--xl > .o-layout__item {
		flex-basis: calc(100% / 3);
		max-width: calc(100% / 3);
	}
	
	.u-grids-4--xl > .o-layout__item {
		flex-basis: calc(100% / 4);
		max-width: calc(100% / 4);
	}
	
	.u-grids-5--xl > .o-layout__item {
		flex-basis: calc(100% / 5);
		max-width: calc(100% / 5);
	}
	
	.u-grids-6--xl > .o-layout__item {
		flex-basis: calc(100% / 6);
		max-width: calc(100% / 6);
	}
	
	.u-grids-7--xl > .o-layout__item {
		flex-basis: calc(100% / 7);
		max-width: calc(100% / 7);
	}
	
	.u-grids-8--xl > .o-layout__item {
		flex-basis: calc(100% / 8);
		max-width: calc(100% / 8);
	}
	
	.u-grids-9--xl > .o-layout__item {
		flex-basis: calc(100% / 9);
		max-width: calc(100% / 9);
	}
	
	.u-grids-10--xl > .o-layout__item {
		flex-basis: calc(100% / 10);
		max-width: calc(100% / 10);
	}
	
	.u-grids-11--xl > .o-layout__item {
		flex-basis: calc(100% / 11);
		max-width: calc(100% / 11);
	}
	
	.u-grids-12--xl > .o-layout__item {
		flex-basis: calc(100% / 12);
		max-width: calc(100% / 12);
	}
}


/* Wide-Screen Breakpoint [90em = 1440px]
   =========================================== */
@media screen and (min-width: 90em) {
	.u-grids-1--w > .o-layout__item {
		flex-basis: 100%;
		max-width: 100%;
	}
	
	.u-grids-2--w > .o-layout__item {
		flex-basis: calc(100% / 2);
		max-width: calc(100% / 2);
	}
	
	.u-grids-3--w > .o-layout__item {
		flex-basis: calc(100% / 3);
		max-width: calc(100% / 3);
	}
	
	.u-grids-4--w > .o-layout__item {
		flex-basis: calc(100% / 4);
		max-width: calc(100% / 4);
	}
	
	.u-grids-5--w > .o-layout__item {
		flex-basis: calc(100% / 5);
		max-width: calc(100% / 5);
	}
	
	.u-grids-6--w > .o-layout__item {
		flex-basis: calc(100% / 6);
		max-width: calc(100% / 6);
	}
	
	.u-grids-7--w > .o-layout__item {
		flex-basis: calc(100% / 7);
		max-width: calc(100% / 7);
	}
	
	.u-grids-8--w > .o-layout__item {
		flex-basis: calc(100% / 8);
		max-width: calc(100% / 8);
	}
	
	.u-grids-9--w > .o-layout__item {
		flex-basis: calc(100% / 9);
		max-width: calc(100% / 9);
	}
	
	.u-grids-10--w > .o-layout__item {
		flex-basis: calc(100% / 10);
		max-width: calc(100% / 10);
	}
	
	.u-grids-11--w > .o-layout__item {
		flex-basis: calc(100% / 11);
		max-width: calc(100% / 11);
	}
	
	.u-grids-12--w > .o-layout__item {
		flex-basis: calc(100% / 12);
		max-width: calc(100% / 12);
	}
}
```

**Comment by influxweb** [comment]
**`mm5/themes/shadows/core/css/utilities/widths.css`**
```css
/* ==========================================================================
   UTILITIES / WIDTHS
   ========================================================================== */

/**
 * A series of utility classes that give a fluid width to whichever element
 * they are applied to, media breakpoints are included.
 */

/* Mobile First
   =========================================== */
/**
 * Width size modifiers.
 */
.u-width-1 {
	flex-basis: calc(100% / 12 * 1);
	max-width: calc(100% / 12 * 1);
}

.u-width-2 {
	flex-basis: calc(100% / 12 * 2);
	max-width: calc(100% / 12 * 2);
}

.u-width-3 {
	flex-basis: calc(100% / 12 * 3);
	max-width: calc(100% / 12 * 3);
}

.u-width-4 {
	flex-basis: calc(100% / 12 * 4);
	max-width: calc(100% / 12 * 4);
}

.u-width-5 {
	flex-basis: calc(100% / 12 * 5);
	max-width: calc(100% / 12 * 5);
}

.u-width-6 {
	flex-basis: calc(100% / 12 * 6);
	max-width: calc(100% / 12 * 6);
}

.u-width-7 {
	flex-basis: calc(100% / 12 * 7);
	max-width: calc(100% / 12 * 7);
}

.u-width-8 {
	flex-basis: calc(100% / 12 * 8);
	max-width: calc(100% / 12 * 8);
}

.u-width-9 {
	flex-basis: calc(100% / 12 * 9);
	max-width: calc(100% / 12 * 9);
}

.u-width-10 {
	flex-basis: calc(100% / 12 * 10);
	max-width: calc(100% / 12 * 10);
}

.u-width-11 {
	flex-basis: calc(100% / 12 * 11);
	max-width: calc(100% / 12 * 11);
}

.u-width-12 {
	flex-basis: calc(100% / 12 * 12);
	max-width: calc(100% / 12 * 12);
}


/**
 * Offset size modifiers.
 */
.u-offset-1 {
	margin-left: calc(100% / 12 * 1);
}

.u-offset-2 {
	margin-left: calc(100% / 12 * 2);
}

.u-offset-3 {
	margin-left: calc(100% / 12 * 3);
}

.u-offset-4 {
	margin-left: calc(100% / 12 * 4);
}

.u-offset-5 {
	margin-left: calc(100% / 12 * 5);
}

.u-offset-6 {
	margin-left: calc(100% / 12 * 6);
}

.u-offset-7 {
	margin-left: calc(100% / 12 * 7);
}

.u-offset-8 {
	margin-left: calc(100% / 12 * 8);
}

.u-offset-9 {
	margin-left: calc(100% / 12 * 9);
}

.u-offset-10 {
	margin-left: calc(100% / 12 * 10);
}

.u-offset-11 {
	margin-left: calc(100% / 12 * 11);
}


/* Small Breakpoint [40em = 640px]
   =========================================== */
@media screen and (min-width: 40em) {
	.u-width-1--s {
		flex-basis: calc(100% / 12 * 1);
		max-width: calc(100% / 12 * 1);
	}
	
	.u-width-2--s {
		flex-basis: calc(100% / 12 * 2);
		max-width: calc(100% / 12 * 2);
	}
	
	.u-width-3--s {
		flex-basis: calc(100% / 12 * 3);
		max-width: calc(100% / 12 * 3);
	}
	
	.u-width-4--s {
		flex-basis: calc(100% / 12 * 4);
		max-width: calc(100% / 12 * 4);
	}
	
	.u-width-5--s {
		flex-basis: calc(100% / 12 * 5);
		max-width: calc(100% / 12 * 5);
	}
	
	.u-width-6--s {
		flex-basis: calc(100% / 12 * 6);
		max-width: calc(100% / 12 * 6);
	}
	
	.u-width-7--s {
		flex-basis: calc(100% / 12 * 7);
		max-width: calc(100% / 12 * 7);
	}
	
	.u-width-8--s {
		flex-basis: calc(100% / 12 * 8);
		max-width: calc(100% / 12 * 8);
	}
	
	.u-width-9--s {
		flex-basis: calc(100% / 12 * 9);
		max-width: calc(100% / 12 * 9);
	}
	
	.u-width-10--s {
		flex-basis: calc(100% / 12 * 10);
		max-width: calc(100% / 12 * 10);
	}
	
	.u-width-11--s {
		flex-basis: calc(100% / 12 * 11);
		max-width: calc(100% / 12 * 11);
	}
	
	.u-width-12--s {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
	
	
	/**
	 * Offset size modifiers.
	 */
	.u-offset-1--s {
		margin-left: calc(100% / 12 * 1);
	}
	
	.u-offset-2--s {
		margin-left: calc(100% / 12 * 2);
	}
	
	.u-offset-3--s {
		margin-left: calc(100% / 12 * 3);
	}
	
	.u-offset-4--s {
		margin-left: calc(100% / 12 * 4);
	}
	
	.u-offset-5--s {
		margin-left: calc(100% / 12 * 5);
	}
	
	.u-offset-6--s {
		margin-left: calc(100% / 12 * 6);
	}
	
	.u-offset-7--s {
		margin-left: calc(100% / 12 * 7);
	}
	
	.u-offset-8--s {
		margin-left: calc(100% / 12 * 8);
	}
	
	.u-offset-9--s {
		margin-left: calc(100% / 12 * 9);
	}
	
	.u-offset-10--s {
		margin-left: calc(100% / 12 * 10);
	}
	
	.u-offset-11--s {
		margin-left: calc(100% / 12 * 11);
	}
}


/* Medium Breakpoint [48em = 768px]
   =========================================== */
@media screen and (min-width: 48em) {
	.u-width-1--m {
		flex-basis: calc(100% / 12 * 1);
		max-width: calc(100% / 12 * 1);
	}
	
	.u-width-2--m {
		flex-basis: calc(100% / 12 * 2);
		max-width: calc(100% / 12 * 2);
	}
	
	.u-width-3--m {
		flex-basis: calc(100% / 12 * 3);
		max-width: calc(100% / 12 * 3);
	}
	
	.u-width-4--m {
		flex-basis: calc(100% / 12 * 4);
		max-width: calc(100% / 12 * 4);
	}
	
	.u-width-5--m {
		flex-basis: calc(100% / 12 * 5);
		max-width: calc(100% / 12 * 5);
	}
	
	.u-width-6--m {
		flex-basis: calc(100% / 12 * 6);
		max-width: calc(100% / 12 * 6);
	}
	
	.u-width-7--m {
		flex-basis: calc(100% / 12 * 7);
		max-width: calc(100% / 12 * 7);
	}
	
	.u-width-8--m {
		flex-basis: calc(100% / 12 * 8);
		max-width: calc(100% / 12 * 8);
	}
	
	.u-width-9--m {
		flex-basis: calc(100% / 12 * 9);
		max-width: calc(100% / 12 * 9);
	}
	
	.u-width-10--m {
		flex-basis: calc(100% / 12 * 10);
		max-width: calc(100% / 12 * 10);
	}
	
	.u-width-11--m {
		flex-basis: calc(100% / 12 * 11);
		max-width: calc(100% / 12 * 11);
	}
	
	.u-width-12--m {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
	
	
	/**
	 * Offset size modifiers.
	 */
	.u-offset-1--m {
		margin-left: calc(100% / 12 * 1);
	}
	
	.u-offset-2--m {
		margin-left: calc(100% / 12 * 2);
	}
	
	.u-offset-3--m {
		margin-left: calc(100% / 12 * 3);
	}
	
	.u-offset-4--m {
		margin-left: calc(100% / 12 * 4);
	}
	
	.u-offset-5--m {
		margin-left: calc(100% / 12 * 5);
	}
	
	.u-offset-6--m {
		margin-left: calc(100% / 12 * 6);
	}
	
	.u-offset-7--m {
		margin-left: calc(100% / 12 * 7);
	}
	
	.u-offset-8--m {
		margin-left: calc(100% / 12 * 8);
	}
	
	.u-offset-9--m {
		margin-left: calc(100% / 12 * 9);
	}
	
	.u-offset-10--m {
		margin-left: calc(100% / 12 * 10);
	}
	
	.u-offset-11--m {
		margin-left: calc(100% / 12 * 11);
	}
}


/* Large Breakpoint [60em = 960px]
   =========================================== */
@media screen and (min-width: 60em) {
	.u-width-1--l {
		flex-basis: calc(100% / 12 * 1);
		max-width: calc(100% / 12 * 1);
	}
	
	.u-width-2--l {
		flex-basis: calc(100% / 12 * 2);
		max-width: calc(100% / 12 * 2);
	}
	
	.u-width-3--l {
		flex-basis: calc(100% / 12 * 3);
		max-width: calc(100% / 12 * 3);
	}
	
	.u-width-4--l {
		flex-basis: calc(100% / 12 * 4);
		max-width: calc(100% / 12 * 4);
	}
	
	.u-width-5--l {
		flex-basis: calc(100% / 12 * 5);
		max-width: calc(100% / 12 * 5);
	}
	
	.u-width-6--l {
		flex-basis: calc(100% / 12 * 6);
		max-width: calc(100% / 12 * 6);
	}
	
	.u-width-7--l {
		flex-basis: calc(100% / 12 * 7);
		max-width: calc(100% / 12 * 7);
	}
	
	.u-width-8--l {
		flex-basis: calc(100% / 12 * 8);
		max-width: calc(100% / 12 * 8);
	}
	
	.u-width-9--l {
		flex-basis: calc(100% / 12 * 9);
		max-width: calc(100% / 12 * 9);
	}
	
	.u-width-10--l {
		flex-basis: calc(100% / 12 * 10);
		max-width: calc(100% / 12 * 10);
	}
	
	.u-width-11--l {
		flex-basis: calc(100% / 12 * 11);
		max-width: calc(100% / 12 * 11);
	}
	
	.u-width-12--l {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
	
	
	/**
	 * Offset size modifiers.
	 */
	.u-offset-1--l {
		margin-left: calc(100% / 12 * 1);
	}
	
	.u-offset-2--l {
		margin-left: calc(100% / 12 * 2);
	}
	
	.u-offset-3--l {
		margin-left: calc(100% / 12 * 3);
	}
	
	.u-offset-4--l {
		margin-left: calc(100% / 12 * 4);
	}
	
	.u-offset-5--l {
		margin-left: calc(100% / 12 * 5);
	}
	
	.u-offset-6--l {
		margin-left: calc(100% / 12 * 6);
	}
	
	.u-offset-7--l {
		margin-left: calc(100% / 12 * 7);
	}
	
	.u-offset-8--l {
		margin-left: calc(100% / 12 * 8);
	}
	
	.u-offset-9--l {
		margin-left: calc(100% / 12 * 9);
	}
	
	.u-offset-10--l {
		margin-left: calc(100% / 12 * 10);
	}
	
	.u-offset-11--l {
		margin-left: calc(100% / 12 * 11);
	}
}


/* Extra-Large Breakpoint [75em = 1200px]
   =========================================== */
@media screen and (min-width: 75em) {
	.u-width-1--xl {
		flex-basis: calc(100% / 12 * 1);
		max-width: calc(100% / 12 * 1);
	}
	
	.u-width-2--xl {
		flex-basis: calc(100% / 12 * 2);
		max-width: calc(100% / 12 * 2);
	}
	
	.u-width-3--xl {
		flex-basis: calc(100% / 12 * 3);
		max-width: calc(100% / 12 * 3);
	}
	
	.u-width-4--xl {
		flex-basis: calc(100% / 12 * 4);
		max-width: calc(100% / 12 * 4);
	}
	
	.u-width-5--xl {
		flex-basis: calc(100% / 12 * 5);
		max-width: calc(100% / 12 * 5);
	}
	
	.u-width-6--xl {
		flex-basis: calc(100% / 12 * 6);
		max-width: calc(100% / 12 * 6);
	}
	
	.u-width-7--xl {
		flex-basis: calc(100% / 12 * 7);
		max-width: calc(100% / 12 * 7);
	}
	
	.u-width-8--xl {
		flex-basis: calc(100% / 12 * 8);
		max-width: calc(100% / 12 * 8);
	}
	
	.u-width-9--xl {
		flex-basis: calc(100% / 12 * 9);
		max-width: calc(100% / 12 * 9);
	}
	
	.u-width-10--xl {
		flex-basis: calc(100% / 12 * 10);
		max-width: calc(100% / 12 * 10);
	}
	
	.u-width-11--xl {
		flex-basis: calc(100% / 12 * 11);
		max-width: calc(100% / 12 * 11);
	}
	
	.u-width-12--xl {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
	
	
	/**
	 * Offset size modifiers.
	 */
	.u-offset-1--xl {
		margin-left: calc(100% / 12 * 1);
	}
	
	.u-offset-2--xl {
		margin-left: calc(100% / 12 * 2);
	}
	
	.u-offset-3--xl {
		margin-left: calc(100% / 12 * 3);
	}
	
	.u-offset-4--xl {
		margin-left: calc(100% / 12 * 4);
	}
	
	.u-offset-5--xl {
		margin-left: calc(100% / 12 * 5);
	}
	
	.u-offset-6--xl {
		margin-left: calc(100% / 12 * 6);
	}
	
	.u-offset-7--xl {
		margin-left: calc(100% / 12 * 7);
	}
	
	.u-offset-8--xl {
		margin-left: calc(100% / 12 * 8);
	}
	
	.u-offset-9--xl {
		margin-left: calc(100% / 12 * 9);
	}
	
	.u-offset-10--xl {
		margin-left: calc(100% / 12 * 10);
	}
	
	.u-offset-11--xl {
		margin-left: calc(100% / 12 * 11);
	}
}


/* Wide-Screen Breakpoint [90em = 1440px]
   =========================================== */
@media screen and (min-width: 90em) {
	.u-width-1--w {
		flex-basis: calc(100% / 12 * 1);
		max-width: calc(100% / 12 * 1);
	}
	
	.u-width-2--w {
		flex-basis: calc(100% / 12 * 2);
		max-width: calc(100% / 12 * 2);
	}
	
	.u-width-3--w {
		flex-basis: calc(100% / 12 * 3);
		max-width: calc(100% / 12 * 3);
	}
	
	.u-width-4--w {
		flex-basis: calc(100% / 12 * 4);
		max-width: calc(100% / 12 * 4);
	}
	
	.u-width-5--w {
		flex-basis: calc(100% / 12 * 5);
		max-width: calc(100% / 12 * 5);
	}
	
	.u-width-6--w {
		flex-basis: calc(100% / 12 * 6);
		max-width: calc(100% / 12 * 6);
	}
	
	.u-width-7--w {
		flex-basis: calc(100% / 12 * 7);
		max-width: calc(100% / 12 * 7);
	}
	
	.u-width-8--w {
		flex-basis: calc(100% / 12 * 8);
		max-width: calc(100% / 12 * 8);
	}
	
	.u-width-9--w {
		flex-basis: calc(100% / 12 * 9);
		max-width: calc(100% / 12 * 9);
	}
	
	.u-width-10--w {
		flex-basis: calc(100% / 12 * 10);
		max-width: calc(100% / 12 * 10);
	}
	
	.u-width-11--w {
		flex-basis: calc(100% / 12 * 11);
		max-width: calc(100% / 12 * 11);
	}
	
	.u-width-12--w {
		flex-basis: calc(100% / 12 * 12);
		max-width: calc(100% / 12 * 12);
	}
	
	
	/**
	 * Offset size modifiers.
	 */
	.u-offset-1--w {
		margin-left: calc(100% / 12 * 1);
	}
	
	.u-offset-2--w {
		margin-left: calc(100% / 12 * 2);
	}
	
	.u-offset-3--w {
		margin-left: calc(100% / 12 * 3);
	}
	
	.u-offset-4--w {
		margin-left: calc(100% / 12 * 4);
	}
	
	.u-offset-5--w {
		margin-left: calc(100% / 12 * 5);
	}
	
	.u-offset-6--w {
		margin-left: calc(100% / 12 * 6);
	}
	
	.u-offset-7--w {
		margin-left: calc(100% / 12 * 7);
	}
	
	.u-offset-8--w {
		margin-left: calc(100% / 12 * 8);
	}
	
	.u-offset-9--w {
		margin-left: calc(100% / 12 * 9);
	}
	
	.u-offset-10--w {
		margin-left: calc(100% / 12 * 10);
	}
	
	.u-offset-11--w {
		margin-left: calc(100% / 12 * 11);
	}
}
```

**Comment by influxweb** [comment]
**`mm5/themes/shadows/core/css/base/resets.css`**
```css
/* ==========================================================================
   BASE / RESETS
   ========================================================================== */

/**
 * This contains some additional resets and baselines not facilitated by
 * 'normalize.css'. Editing is not recommended.
 */

html {
	box-sizing: border-box;
}


*,
*::before,
*::after {
	box-sizing: inherit;
}





/* Vertical Rhythm
   =========================================== */

/**
 * Apply our base spacing unit as a `margin-bottom` to all block level elements
 * so that we get nice and consistent vertical rhythm very cheaply.
 * http://csswizardry.com/2012/06/single-direction-margin-declarations/
 */
address,
blockquote,
dl,
fieldset,
figure,
form,
h1,
h2,
h3,
h4,
h5,
h6,
menu,
ol,
p,
pre,
summary,
table,
ul {
	margin-top: 0;
	margin-bottom: 16px;
}

fieldset {
	margin-right: 0;
	margin-left: 0;
	padding: 0;
}


/**
 * We'll also indent list elements by the same amount of spacing. Also, we will
 * remove the left padding added by some user-agents.
 */
dd,
ol,
ul {
	margin-left: 16px;
	padding-left: 0;
}

/**
 * Remove trailing margins from nested lists.
 */
li > ol,
li > ul {
	margin-bottom: 0;
}





/**
 * Pseudo Selection
 */
::-moz-selection {
	background: #eaeaea;
	text-shadow: none;
}

::selection {
	background: #eaeaea;
	text-shadow: none;
}

::selection:window-inactive {
	background: #eaeaea;
}

img::selection {
	background: rgba(0, 0, 0, 0);
}

img::-moz-selection {
	background: rgba(0, 0, 0, 0);
}





/**
 * Identify Disabled/Not Allowed Elements
 */
*[disabled] {
	cursor: not-allowed;
}





/**
 * Breakpoints
 * These values will not show up in content, but can be queried by JavaScript
 * to know which breakpoint is active.
 */
body::before {
	display: none;
	content: "xsmall";
	visibility: hidden;
}

@media (min-width: 40em) {
	body::before {
		content: "small";
	}
}

@media (min-width: 48em) {
	body::before {
		content: "medium";
	}
}

@media (min-width: 60em) {
	body::before {
		content: "large";
	}
}

@media (min-width: 75em) {
	body::before {
		content: "xlarge";
	}
}

@media (min-width: 90em) {
	body::before {
		content: "wide";
	}
}
```
